package com.example.lottos;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.navigation.fragment.NavHostFragment;

import com.example.lottos.R; // Ensure your R file is imported
import com.example.lottos.databinding.FragmentGeoLocationMapScreenBinding;
import com.example.lottos.organizer.OrganizerEventManager;
import com.google.android.gms.maps.CameraUpdateFactory;
import com.google.android.gms.maps.GoogleMap;
import com.google.android.gms.maps.OnMapReadyCallback;
import com.google.android.gms.maps.SupportMapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.MarkerOptions;

import java.util.Map;

/**
 * Displays a map with markers for all users who joined a specific event.
 */
public class GeoLocationMapScreen extends Fragment implements OnMapReadyCallback {

    private FragmentGeoLocationMapScreenBinding binding;
    private GoogleMap mMap;
    private String eventId;
    private OrganizerEventManager manager;

    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        binding = FragmentGeoLocationMapScreenBinding.inflate(inflater, container, false);
        return binding.getRoot();
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        // Retrieve the eventId from the navigation arguments
        if (getArguments() != null) {
            // NOTE: This class will be auto-generated by the Navigation component after build.
            GeoLocationMapScreenArgs args = GeoLocationMapScreenArgs.fromBundle(getArguments());
            eventId = args.getEventId();
        }

        manager = new OrganizerEventManager();

        // Get the SupportMapFragment and request the map object
        SupportMapFragment mapFragment = (SupportMapFragment) getChildFragmentManager()
                .findFragmentById(R.id.map_container);

        if (mapFragment != null) {
            mapFragment.getMapAsync(this);
        }

        binding.btnBack.setOnClickListener(v -> NavHostFragment.findNavController(this).navigateUp());
    }

    @Override
    public void onMapReady(GoogleMap googleMap) {
        mMap = googleMap;
        mMap.getUiSettings().setZoomControlsEnabled(true);
        loadEntrantLocations();
    }

    private void loadEntrantLocations() {
        if (eventId == null || manager == null) {
            toast("Error: Event ID is missing.");
            return;
        }

        manager.getEntrantLocations(eventId,
                new OrganizerEventManager.LocationsCallback() {
                    @Override
                    public void onSuccess(Map<String, Map<String, Double>> locations) {
                        if (locations.isEmpty()) {
                            toast("No location data recorded for this event.");
                            mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(0, 0), 2));
                            return;
                        }
                        plotMarkers(locations);
                    }

                    @Override
                    public void onError(Exception e) {
                        toast("Failed to load locations: " + e.getMessage());
                    }
                }
        );
    }

    private void plotMarkers(Map<String, Map<String, Double>> locations) {
        LatLng firstLocation = null;

        for (Map.Entry<String, Map<String, Double>> entry : locations.entrySet()) {
            String userName = entry.getKey();
            Map<String, Double> coords = entry.getValue();

            Double lat = coords.get("latitude");
            Double lon = coords.get("longitude");

            // Filter out default/dummy coordinates (0.0, 0.0)
            if (lat != null && lon != null && (lat != 0.0 || lon != 0.0)) {
                LatLng userLatLng = new LatLng(lat, lon);
                mMap.addMarker(new MarkerOptions().position(userLatLng).title(userName));

                if (firstLocation == null) {
                    firstLocation = userLatLng;
                }
            }
        }

        // Move camera to the first recorded location (if available)
        if (firstLocation != null) {
            mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(firstLocation, 10));
        } else {
            // No valid locations found, center map generically
            mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(39.8283, -98.5795), 2));
            toast("No valid geolocation was captured for entrants.");
        }
    }

    private void toast(String message) {
        if (getContext() != null) {
            Toast.makeText(getContext(), message, Toast.LENGTH_LONG).show();
        }
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;
    }
}